name: gestion_libros
description: "A new Flutter project for LibriDex."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # --- CONECTIVIDAD Y API ---
  # Para buscar libros en Google Books
  http: ^1.2.0
  
  # --- FIREBASE ---
  # Core, Autenticación y Base de Datos (Firestore)
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Registro de Assets (Imágenes del proyecto)
  assets:
    - images/logo.png